title: "Resume"
tagline:  'All about Android'
baseurl: ""
description: 'My personal blog where I share my opinions and take notes of what I have learnt.'

resume_avatar: "true"

github: "https://github.com/allaudin"
author:
  name: M. Allaudin
  url:  https://twitter.com/mallaudin
  email:  mallaudinqazi@gmail.com

permalink:      /:title/
markdown:       kramdown
highlighter:    rouge
paginate: 20

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  enable_coderay: false

sass:
  sass_dir: _sass
  style: compressed

exclude: [README.md, Gemfile, Gemfile.lock, .idea, node_modules,
          gulpfile.js, package.json, _site, Makefile, src, vendor,
          CNAME, LICENSE, Rakefile]

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

google_analytics_id: UA-71498610-3

theme: minima